# Generated by Django 4.0.6 on 2022-08-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='ID')),
                ('order_number', models.IntegerField(blank=True, null=True, verbose_name='Номер заказа')),
                ('order_cost_usd', models.IntegerField(blank=True, null=True, verbose_name='Стоимость заказа, USD')),
                ('order_cost_rub', models.FloatField(blank=True, null=True, verbose_name='Стоимость заказа, RUB')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Срок поставки')),
            ],
            options={
                'verbose_name': 'Детали заказа',
                'verbose_name_plural': 'Детали заказов',
            },
        ),
    ]
