version: '3.7'

services:
  back:
    build: ./kanalservice_back
    container_name: back
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    container_name: db
    env_file:
      - .env.db
    volumes:
      - kanalservice-db:/var/lib/postgresql/data


  ngnix:
    build: ./ngnix
    restart: on-failure
    ports:
      - 1337:80
    depends_on:
      - back

volumes:
  kanalservice-db: