version: '3.7'

services:
  back:
    build: ./kanalservice_back
    container_name: back
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: db
    environment:
      POSTGRES_DB: kanalservice-web,
      POSTGRES_USER: postgres,
      POSTGRES_PASSWORD: app123
    volumes:
      - kanalservice-db:/var/lib/postgresql/data

#
#  ngnix:
#    build: ./ngnix
#    restart: on-failure
#    ports:
#      - 80:80
#    depends_on:
#      - back
#
volumes:
  kanalservice-db: