version: '3.7'

services:
  back:
    build: ./kanalservice_back
    container_name: back
    restart: on-failure
    entrypoint: ["/usr/src/app/entrypoint.sh"]
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.0-alpine
    container_name: db
    env_file:
      - .env.db
    volumes:
      - kanalservice-db:/var/lib/postgresql/data


  ngnix:
    build: ./ngnix
    restart: on-failure
    ports:
      - 1337:80
    depends_on:
      - back

  redis:
    image: redis
    restart: always
    ports:
      - 6380:6379

  celery:
    build: ./kanalservice_back
    restart: always
    entrypoint: ["/usr/src/app/entrypoint_celery.sh"]
    volumes:
      - celery_volume:/usr/src/app/
    env_file:
      - ./kanalservice_back/.env
    depends_on:
      - redis
      - back

  celery-beat:
    build: ./kanalservice_back
    restart: always
    entrypoint: ["/usr/src/app/entrypoint_celery_beat.sh"]
    volumes:
      - celery_volume_beat:/usr/src/app/
    env_file:
      - ./kanalservice_back/.env
    depends_on:
      - redis
      - back
      - celery

volumes:
  kanalservice-db:
  celery_volume:
  celery_volume_beat: